const projectData = [
  {
    title: "AAT",
    description:
      "빅데이터를 분석하여 최적의 수익 실현 타이밍에 매매를 도와주는 인공지능 서비스 웹사이트 입니다.",
    link: "",
    image: "/img/aat_01.jpg",
    gifImage: "/img/aat_01_g.gif",
    technologies: [
      "#React",
      "#TypeScript",
      "#Redux",
      "#Aixos",
      "#SCSS",
      "#반응형",
    ],
    status: "개발중",
    modalContent: {
      title: "AAT",
      date: "작업기간 : 2023.11. ~ 개발중",
      team: "팀 구성 : 프론트엔드 1명, 백엔드 1명, 디자이너 1명, 기획자 2명",
      description:
        "백엔드와의 협업을 경험하면서 ESLint, Prettier, Git 등을 활용하여 프론트엔드와 백엔드 간의 코드 품질을 유지하고 협업 시 발생할 수 있는 문제에 대비하는 경험을 할 수 있었습니다. TypeScript를 사용하여 더욱 견고한 코드베이스를 구축하고, 타입 시스템을 통해 버그를 사전에 방지하고자 노력했습니다. 또한 프로젝트의 복잡한 구조로 인해 Redux Toolkit 라이브러리를 도입하여 상태 관리를 보다 효율적으로 처리했습니다.",
      link: "",
      features: [
        "JWT 토큰을 이용해서 로그인 인증 구현",
        "로그인 여부에 따른 리다이렉트 구현",
        "회원가입/로그인시 유효성 검사 기능 구현",
        "Axios를 사용하여 API 요청에 대한 응답 처리",
        "데이터 시각화를 위한 대시보드, 차트 기능 구현",
        "게시판 리스트 및 검색 기능 구현",
        "페이지네이션 구현",
        "Redux-toolkit을 활용한 전역 상태관리" /*  */,
        "SCSS를 사용하여 스타일을 적용",
        "반응형 웹 개발 및 크로스 브라우징 개발",
      ],
      skill: ["Vite", "React", "TypeScript", "Redux Toolkit", "SCSS"],
      screen: [
        "로그인",
        "입금신청 대시보드",
        "그래프 대시보드",
        "트리구조 대시보드",
        "게시판",
        "반응형",
      ],
      image: [
        "/img/aat_01_g.gif",
        "/img/aat_02_g.gif",
        "/img/aat_03.jpg",
        "/img/aat_07.jpg",
        "/img/aat_05.jpg",
        "/img/aat_13.jpg",
      ],
      screenText: [
        "<react-hook-form> 라이브러리를 사용하여 <유효성 검사>를 하였고, <로그인 여부에 따라 자동으로 리다이렉트>되도록 구현했습니다.",
        "현재 자산의 입금범위에 따른 등급 변화를 <그래프로 시각화>하여 미리 보여주는 UI/UX를 구현했습니다.",
        "원형 그래프를 구현하기 위해 <RadialChart> 라이브러리를 활용하였고, 현재 회원 등급과 다음 등급까지 필요한 남은 USDT를 보여주는 <대시보드를 구현>했습니다.",
        "<react-d3-tree> 라이브러리를 활용하여 추천 등록 내역을 한 번에 보기 위한 <트리 구조를 구현>했습니다.",
        "게시판에서 사용자가 원하는 <데이터를 검색>할 수 있도록 구현하고, 검색 결과를 페이지별로 나누어 표시할 수 있는 <페이지네이션을 구현>했습니다.",
        "<반응형 웹 개발>과 <크로스 브라우징>으로 개발하였습니다.",
      ],
      contribution: ["dddd"],
    },
  },
  {
    title: "PetCare Lab",
    description:
      "스마트 배변판으로 반려동물의 소변검사를 통해집에서 건강상태를 손쉽게 진단할 수 있는 펫케어 서비스 웹사이트 입니다.",
    link: "https://petcarelab.net/",
    image: "/img/petcare_08_g01.jpg",
    gifImage: "/img/petcare_08_g.gif",
    technologies: ["#React", "#JavaScript", "#SCSS", "#반응형"],
    modalContent: {
      title: "PetCare Lab",
      date: "2023.6. ~ 2023.6.",
      team: "팀 구성 : 프론트엔드 1명, 디자이너 1명, 기획자 1명",
      description:
        "원페이지 스크롤 형태의 플랫폼 소개 웹사이트 입니다. react-intl 라이브러리를 사용하여 다국어 서비스를 구현해 볼 수 있었습니다. 또한 react-slick 라이브러리와 aos 라이브러리를 사용하여 다양한 동적인 요소를 구현했습니다. github와 연동되는 호스팅 플랫폼 Netlify를 활용하여 웹사이트를 손쉽게 배포하고 유지 보수할 수 있었습니다.",
      link: "https://petcarelab.net/",
      features: [
        "react-intl을 활용한 다국어 구현(KOR, ENG)",
        "GNB 메뉴 클릭 시 특정 컴포넌트로 스크롤 이동하는 기능 구현",
        "aos을 활용한 스크롤 애니메이션 구현",
        "react-slick을 활용한 슬라이드 구현",
        "Email.js을 활용한 고객의 문의사항을 자사 이메일로 받을 수 있도록 연동",
        "반응형 웹 개발 및 크로스 브라우징 개발",
        " Netlify로 배포, 유지 보수",
      ],
      skill: ["React", "JavaScript", "SCSS", "Netlify", "반응형"],
      screen: [
        "다국어 서비스",
        "원페이지 스크롤",
        "슬라이드",
        "문의사항 이메일 연동",
        "반응형",
      ],
      image: [
        "/img/petcare_08_g01.jpg",
        "/img/petcare_08_g.gif",
        "/img/aat_03.jpg",
        "/img/aat_07.jpg",
        "/img/aat_05.jpg",
        "/img/aat_13.jpg",
      ],
      screenText: [
        "<react-intl> 라이브러리를 활용하여 <다국어 서비스>를 구현했습니다.",
        "GNB 메뉴 클릭 시 특정 컴포넌트로 스크롤 이동하는 <원페이지 스크롤> 기능 구현을했습니다.",
        "<react-slick> 라이브러리를 활용하여 <슬라이드> 동작을 구현했습니다.",
        "<Email.js>을 활용하여 고객의 <문의사항을 자사 이메일>로 받을 수 있도록 연동하였습니다.",
        "<반응형 웹 개발>과 <크로스 브라우징>으로 개발하였습니다.",
      ],
    },
  },
  {
    title: "MBTCs",
    description: "Ai-Dapps 공식 홈페이지 입니다.",
    link: "https://mbtcsuper.com/",
    image: "/img/mbtcs_01.jpg",
    gifImage: "/img/petcare_08_g.gif",
    technologies: ["#React", "#JavaScript", "#SCSS", "#반응형"],
    modalContent: {
      title: "MBTCs",
      date: "2023.5. ~ 2023.5.",
      team: "팀 구성 : 프론트엔드 1명, 디자이너 1명, 기획자 1명",
      description:
        "스마트 배변판으로 반려동물의 소변검사를 통해집에서 건강상태를 손쉽게 진단할 수 있는 펫케어 서비스 웹사이트 입니다.",
      link: "https://mbtcsuper.com/",
      features: [
        "GNB 메뉴 클릭 시 특정 컴포넌트로 스크롤 이동하는 기능 구현",
        "aos을 활용한 스크롤 애니메이션 구현",
        "react-slick을 활용한 슬라이드 구현",
        "반응형 웹 개발 및 크로스 브라우징 개발",
        " Netlify로 배포, 유지 보수",
      ],
      skill: ["React", "JavaScript", "SCSS", "Netlify", "반응형"],
      screen: [
        "다국어 서비스",
        "원페이지 스크롤",
        "슬라이드",
        "문의사항 이메일 연동",
        "반응형",
      ],
      image: [
        "/img/petcare_08_g01.jpg",
        "/img/petcare_08_g.gif",
        "/img/aat_03.jpg",
        "/img/aat_07.jpg",
        "/img/aat_05.jpg",
        "/img/aat_13.jpg",
      ],
      screenText: [
        "<react-intl> 라이브러리를 활용하여 <다국어 서비스>를 구현했습니다.",
        "GNB 메뉴 클릭 시 특정 컴포넌트로 스크롤 이동하는 <원페이지 스크롤> 기능 구현을했습니다.",
        "<react-slick> 라이브러리를 활용하여 <슬라이드> 동작을 구현했습니다.",
        "<Email.js>을 활용하여 고객의 <문의사항을 자사 이메일>로 받을 수 있도록 연동하였습니다.",
        "<반응형 웹 개발>과 <크로스 브라우징>으로 개발하였습니다.",
      ],
    },
  },
  {
    title: "ILSHIN",
    description:
      "기존의 일신방직 홈페이지를 UI/UX를 개선하여 리뉴얼한 홈페이지입니다.",
    link: "http://skykwon1004.dothome.co.kr/",
    image: "/img/ilshin_01.jpg",
    gifImage: "/img/petcare_08_g.gif",
    technologies: ["#HTML", "#JQuery", "#CSS", "#그누보드", "#반응형"],
    status: "개발중",
    modalContent: {
      title: "ILSHIN",
      date: "2023.11. ~ 개발중",
      features: [
        "데이터 시각화를 위한 대시보드, 차트 기능 구현",
        "회원가입/로그인시 유효성 검사 기능 구현",
      ],
      skill: ["Vite", "React", "TypeScript", "Redux Toolkit", "SCSS"],
    },
  },
  {
    title: "About Movie",
    description:
      "영화 Open API를 활용하여 영화를 장르별로 구분하고 영화 검색이 가능한 서비스입니다.",
    link: "http://skykwon1004.dothome.co.kr/",
    image: "/img/am_01.jpg",
    gifImage: "/img/petcare_08_g.gif",
    technologies: ["#React", "#JavaScript", "#SCSS"],
    status: "개발중",
    modalContent: {
      title: "About Movie",
      date: "2023.03.08 ~ 2023.03.14",
      features: [
        "데이터 시각화를 위한 대시보드, 차트 기능 구현",
        "회원가입/로그인시 유효성 검사 기능 구현",
      ],
      skill: ["Vite", "React", "TypeScript", "Redux Toolkit", "SCSS"],
    },
  },
  {
    title: "부산 맛집 지도",
    description:
      "공공데이터 API를 이용하여 부산 맛집을 지도에서 한 번에 볼 수 있도록 만든 서비스입니다.",
    link: "https://skykwon1004.github.io/react_busan_restauran/",
    image: "/img/busan_food_01.jpg",
    gifImage: "/img/petcare_08_g.gif",
    technologies: ["#React", "#JavaScript", "#SCSS"],
    status: "개발중",
    modalContent: {
      title: "부산 맛집 지도",
      date: "2023.03.08 ~ 2023.03.14",
      features: [
        "데이터 시각화를 위한 대시보드, 차트 기능 구현",
        "회원가입/로그인시 유효성 검사 기능 구현",
      ],
      skill: ["Vite", "React", "TypeScript", "Redux Toolkit", "SCSS"],
    },
  },
];

export default projectData;
